Unify conversion functions
byztxt/byzantine-majority-text pull request #24
Opened 2023-01-23 21:12 UTC by countingpine

Hi.
This PR unifies the `convert_book_[no_]accents` and `convert_all_books_to_unicode_[no_]accents` functions, in order to reduce repeated code, and make the differences between the functions more obvious.

It may be worth noting that it highlights some arbitrary-seeming differences, like doing one verse per line and omitting Acts 24 and the PA when accents are dropped.  I don't know if that's intentional.

I think further possibilities for unifying/streamlining the functions and enabling more customisation are possible, but may involve a lot of extra function parameters: e.g. file paths, extensions, making one verse per line, and including/excluding the two extra passages.

If these are desirable, it might be worth finding a better way to set and pass options around.

I hope this PR is helpful to people.

2023-01-23 21:56 UTC, normansimonr requested changes
Hey @countingpine thanks a lot for this PR! The code is definitely neater now! I requested a couple of changes. Once that's done, I will merge!

------

Re: your comments:

> It may be worth noting that it highlights some arbitrary-seeming differences, like doing one verse per line and omitting Acts 24 and the PA when accents are dropped. I don't know if that's intentional.

1. The one verse per line thing was included because the ASC files split a single verse into several lines (something that the CCT files don't do). The ASC files are the non-accented versions, the CCTs are the accented versions.
2. The ASC files don't include the variants for Acts 24 and the _Pericope Adulterae_ because they don't include any variants whatsoever. If you go to Acts 24 and John 8, you will see the texts there, only with no variants associated.

With that in mind, do you think it would make sense to change

```python
def read_book_lines(path, one_verse_one_line)
```

to 

```python
def read_book_lines(path, drop_accents)
```
?

Thanks!

2023-01-23 21:56 UTC, normansimonr commented on scripts/csv_converter.py
> +def read_book_lines(path, one_verse_one_line):
While you're at it, can you add a docstring to this function?

2023-01-24 22:49 UTC, countingpine commented
Hi @normansimonr, thanks for your helpful feedback.

I actually see things a lot more clearly now, and I understand that both differences are actually motivated not by a desired change in the output format, but because they're essentially parsing two different formats of input texts.

I also realise that `drop_accents` isn't an accurate name for the new parameter.  I think it would be improved by calling it `no_accents`, or perhaps `unaccented`.

Your suggestion to rename the `one_verse_one_line` parameter would definitely be an improvement in clarity.  I thought `one_verse_one_line` captured the purpose more clearly, but I was never really that comfortable with passing `one_verse_one_line=drop_accents`..  Now I see that it makes more sense for an `unaccented` parameter to control how the file is parsed anyway.

I will add the necessary docstring to the new function.

I also think that it's worth adding a comment later on to explain why, as you've said, AC24 and PA are only included for the accented inputs.

2023-01-25 16:13 UTC, countingpine commented
I decided in the end, the best thing was to simply go for `accents`.  It involved rearranging some `if` blocks, but I think the overall result is clearer.  I also added a few more comments.

If you're completely happy with everything, then feel free to accept.  Or alternatively to give more feedback/requests.

2023-01-25 18:47 UTC, normansimonr commented
@countingpine Looks awesome! You've written some beautiful Python code there! Thanks a lot!

2023-01-25 18:47 UTC, normansimonr approved these changes

2023-01-25 18:47 UTC, merged